version: "3"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - APP_API_URL=localhost:8000
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - "todo-db"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://todo-db:5432/todo-app
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=dbPass123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  todo-db:
    container_name: database
    image: "postgres:13"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dbPass123
      - POSTGRES_DB=todo-app
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
