version: "3"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - "database"
    links:
      - app-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/gromyk
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=user
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  database:
    container_name: database
    image: "postgres:13"
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=user
      - POSTGRES_DB=gromyk